name: Deploy to GitHub Pages

# Запуск при пуше в main ветку
on:
  push:
    branches:
      - main  # или master, в зависимости от вашей основной ветки

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Prepare files
        run: |
          # Создаем структуру директорий
          mkdir -p dist/css dist/js
          # Копируем файлы
          cp index.html dist/
          cp styles.css dist/css/
          cp -r js/* dist/js/ || true
          cp -r static dist/ || true
          # Создаем .nojekyll
          touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          commit_message: "Deploy static files to GitHub Pages" 